# Generated by Django 4.0.4 on 2022-05-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TICKER', models.CharField(max_length=100)),
                ('DTYYYYMMDD', models.IntegerField(blank=True, null=True)),
                ('FIRST', models.IntegerField(blank=True, null=True)),
                ('HIGH', models.IntegerField(blank=True, null=True)),
                ('LOW', models.IntegerField(blank=True, null=True)),
                ('CLOSE', models.IntegerField(blank=True, null=True)),
                ('VALUE', models.IntegerField(blank=True, null=True)),
                ('VOL', models.IntegerField(blank=True, null=True)),
                ('OPENINT', models.IntegerField(blank=True, null=True)),
                ('PER', models.IntegerField(blank=True, null=True)),
                ('OPEN', models.IntegerField(blank=True, null=True)),
                ('LAST', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
