# Generated by Django 4.0.4 on 2022-05-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='PER',
            field=models.CharField(max_length=5),
        ),
    ]
